-- ============================================================================
-- HOMEX - MODELO FINAL DE BASE DE DATOS (REVISION 2)
-- PostgreSQL
--
-- Decisiones principales incorporadas:
--   * Sin tablas auth_user/auth_group: Django las creara posteriormente.
--   * Sin created_at / updated_at en este script: Django los incorporara.
--   * created_by_id / updated_by_id solo donde la trazabilidad aporta valor.
--   * Maestros usan activo; documentos usan estados de negocio.
--   * Sin deleted_at / deleted_by_id.
--   * Los muebles a medida NO son productos maestros.
--   * Sillas, pisos y productos OTRO son productos maestros y manejan stock.
--   * El stock se modifica exclusivamente mediante movimientos_stock.
--   * movimientos_stock es inmutable: no admite UPDATE ni DELETE.
--   * Pisos: stock y venta exclusivamente en CAJAS; los m2 son informativos.
--   * Aprobar una proforma crea en la misma transaccion un PEDIDO CONFIRMADO.
--   * La confirmacion descuenta stock; si no existe stock suficiente, falla toda
--     la aprobacion de la proforma y no se modifica ninguna existencia.
--   * La captura NLP funciona producto por producto.
-- ============================================================================

BEGIN;

SET search_path TO public;

-- ============================================================================
-- 1. CATALOGO UNIVERSAL
-- ============================================================================

CREATE TABLE catalogo_conceptos (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo          VARCHAR(80) NOT NULL UNIQUE,
    descripcion     TEXT,
    activo          BOOLEAN NOT NULL DEFAULT TRUE,
    created_by_id   BIGINT,
    updated_by_id   BIGINT
);

CREATE TABLE catalogo_valores (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    concepto_id     BIGINT NOT NULL REFERENCES catalogo_conceptos(id),
    codigo          VARCHAR(80) NOT NULL,
    nombre          VARCHAR(150) NOT NULL,
    activo          BOOLEAN NOT NULL DEFAULT TRUE,
    created_by_id   BIGINT,
    updated_by_id   BIGINT,
    CONSTRAINT uq_catalogo_valor_codigo UNIQUE (concepto_id, codigo)
);

CREATE INDEX ix_catalogo_valores_concepto ON catalogo_valores(concepto_id);
CREATE INDEX ix_catalogo_valores_activo ON catalogo_valores(activo);

-- ============================================================================
-- 2. CLIENTES
-- ============================================================================

CREATE TABLE clientes (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_cliente_id BIGINT NOT NULL REFERENCES catalogo_valores(id),
    nombres         VARCHAR(150),
    apellidos       VARCHAR(150),
    empresa         VARCHAR(200),
    celular         VARCHAR(40),
    direccion       TEXT,
    observaciones   TEXT,
    activo          BOOLEAN NOT NULL DEFAULT TRUE,
    created_by_id   BIGINT,
    updated_by_id   BIGINT
);

CREATE INDEX ix_clientes_tipo ON clientes(tipo_cliente_id);
CREATE INDEX ix_clientes_activo ON clientes(activo);
CREATE INDEX ix_clientes_empresa ON clientes(empresa);

-- ============================================================================
-- 3. PRODUCTOS
-- ============================================================================

CREATE TABLE productos (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoria_id    BIGINT NOT NULL REFERENCES catalogo_valores(id),
    sku             VARCHAR(80) UNIQUE,
    nombre          VARCHAR(200) NOT NULL,
    precio_lista    NUMERIC(12,2) NOT NULL DEFAULT 0,
    stock           NUMERIC(12,3) NOT NULL DEFAULT 0,
    unidad_stock_id BIGINT NOT NULL REFERENCES catalogo_valores(id),
    activo          BOOLEAN NOT NULL DEFAULT TRUE,
    observaciones   TEXT,
    created_by_id   BIGINT,
    updated_by_id   BIGINT,
    CONSTRAINT ck_productos_precio_lista_nonnegative CHECK (precio_lista >= 0),
    CONSTRAINT ck_productos_stock_nonnegative CHECK (stock >= 0)
);

CREATE INDEX ix_productos_categoria ON productos(categoria_id);
CREATE INDEX ix_productos_unidad_stock ON productos(unidad_stock_id);
CREATE INDEX ix_productos_activo ON productos(activo);
CREATE INDEX ix_productos_nombre ON productos(nombre);

CREATE TABLE productos_silla (
    producto_id             BIGINT PRIMARY KEY REFERENCES productos(id) ON DELETE CASCADE,
    marca_id                BIGINT REFERENCES catalogo_valores(id),
    modelo                  VARCHAR(150),
    color_primario_id       BIGINT REFERENCES catalogo_valores(id),
    color_secundario_id     BIGINT REFERENCES catalogo_valores(id),
    especificaciones        JSONB,
    created_by_id           BIGINT,
    updated_by_id           BIGINT,
    CONSTRAINT ck_silla_color_secundario_requiere_primario CHECK (
        color_secundario_id IS NULL OR color_primario_id IS NOT NULL
    ),
    CONSTRAINT ck_silla_colores_distintos CHECK (
        color_primario_id IS NULL OR color_secundario_id IS NULL OR color_primario_id <> color_secundario_id
    ),
    CONSTRAINT ck_silla_especificaciones_objeto CHECK (
        especificaciones IS NULL OR jsonb_typeof(especificaciones) = 'object'
    )
);

CREATE TABLE productos_piso (
    producto_id         BIGINT PRIMARY KEY REFERENCES productos(id) ON DELETE CASCADE,
    marca_id            BIGINT REFERENCES catalogo_valores(id),
    modelo              VARCHAR(150),
    tipo_id             BIGINT REFERENCES catalogo_valores(id),
    material_id         BIGINT REFERENCES catalogo_valores(id),
    diseno_id           BIGINT REFERENCES catalogo_valores(id),
    espesor_mm          NUMERIC(8,2),
    acabado_id          BIGINT REFERENCES catalogo_valores(id),
    largo_mm            NUMERIC(10,2),
    ancho_mm            NUMERIC(10,2),
    m2_por_caja         NUMERIC(10,4),
    created_by_id       BIGINT,
    updated_by_id       BIGINT,
    CONSTRAINT ck_piso_espesor_positive CHECK (espesor_mm IS NULL OR espesor_mm > 0),
    CONSTRAINT ck_piso_largo_positive CHECK (largo_mm IS NULL OR largo_mm > 0),
    CONSTRAINT ck_piso_ancho_positive CHECK (ancho_mm IS NULL OR ancho_mm > 0),
    CONSTRAINT ck_piso_m2_caja_positive CHECK (m2_por_caja IS NULL OR m2_por_caja > 0)
);

CREATE TABLE productos_descuento (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id     BIGINT NOT NULL UNIQUE REFERENCES productos(id),
    precio_antes    NUMERIC(12,2) NOT NULL,
    precio_ahora    NUMERIC(12,2) NOT NULL,
    fecha_inicio    DATE,
    fecha_fin       DATE,
    activo          BOOLEAN NOT NULL DEFAULT TRUE,
    created_by_id   BIGINT,
    updated_by_id   BIGINT,
    CONSTRAINT ck_descuento_precios_nonnegative CHECK (precio_antes >= 0 AND precio_ahora >= 0),
    CONSTRAINT ck_descuento_precio_reducido CHECK (precio_ahora < precio_antes),
    CONSTRAINT ck_descuento_fechas CHECK (fecha_fin IS NULL OR fecha_inicio IS NULL OR fecha_fin >= fecha_inicio)
);

-- ============================================================================
-- 4. PROFORMAS
-- ============================================================================

CREATE TABLE proformas (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero              BIGINT NOT NULL UNIQUE,
    cliente_id          BIGINT NOT NULL REFERENCES clientes(id),
    vendedor_id         BIGINT NOT NULL,
    estado_id           BIGINT NOT NULL REFERENCES catalogo_valores(id),
    titulo              VARCHAR(250),
    fecha               DATE NOT NULL DEFAULT CURRENT_DATE,
    plazo_entrega       VARCHAR(100),
    validez_oferta      SMALLINT,
    porcentaje_adelanto NUMERIC(5,2),
    moneda_id           BIGINT NOT NULL REFERENCES catalogo_valores(id),
    subtotal            NUMERIC(14,2) NOT NULL DEFAULT 0,
    descuento_total     NUMERIC(14,2) NOT NULL DEFAULT 0,
    total               NUMERIC(14,2) NOT NULL DEFAULT 0,
    observaciones       TEXT,
    created_by_id       BIGINT,
    updated_by_id       BIGINT,
    CONSTRAINT ck_proforma_validez_nonnegative CHECK (validez_oferta IS NULL OR validez_oferta >= 0),
    CONSTRAINT ck_proforma_adelanto CHECK (
        porcentaje_adelanto IS NULL OR (porcentaje_adelanto >= 0 AND porcentaje_adelanto <= 100)
    ),
    CONSTRAINT ck_proforma_importes CHECK (
        subtotal >= 0 AND descuento_total >= 0 AND total >= 0
    )
);

CREATE INDEX ix_proformas_cliente ON proformas(cliente_id);
CREATE INDEX ix_proformas_vendedor ON proformas(vendedor_id);
CREATE INDEX ix_proformas_estado ON proformas(estado_id);
CREATE INDEX ix_proformas_fecha ON proformas(fecha);

CREATE TABLE proformas_detalle (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proforma_id       BIGINT NOT NULL REFERENCES proformas(id) ON DELETE RESTRICT,
    tipo_item_id      BIGINT NOT NULL REFERENCES catalogo_valores(id),
    producto_id       BIGINT REFERENCES productos(id),
    nombre            VARCHAR(250) NOT NULL,
    descripcion       TEXT,
    cantidad          NUMERIC(12,3) NOT NULL,
    unidad_id         BIGINT NOT NULL REFERENCES catalogo_valores(id),
    precio_unitario   NUMERIC(12,2) NOT NULL,
    descuento         NUMERIC(12,2) NOT NULL DEFAULT 0,
    total             NUMERIC(14,2) NOT NULL DEFAULT 0,
    CONSTRAINT ck_detalle_cantidad_positive CHECK (cantidad > 0),
    CONSTRAINT ck_detalle_precio_nonnegative CHECK (precio_unitario >= 0),
    CONSTRAINT ck_detalle_descuento_nonnegative CHECK (descuento >= 0),
    CONSTRAINT ck_detalle_total_nonnegative CHECK (total >= 0)
);

CREATE INDEX ix_proformas_detalle_proforma ON proformas_detalle(proforma_id);
CREATE INDEX ix_proformas_detalle_producto ON proformas_detalle(producto_id);
CREATE INDEX ix_proformas_detalle_tipo ON proformas_detalle(tipo_item_id);

CREATE TABLE especificaciones_mueble (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proforma_detalle_id   BIGINT NOT NULL UNIQUE REFERENCES proformas_detalle(id) ON DELETE CASCADE,
    tipo_mueble_id        BIGINT REFERENCES catalogo_valores(id),
    espesor               JSONB,
    color_principal       VARCHAR(150),
    color_secundario      VARCHAR(150),
    dimensiones           JSONB,
    accesorios            JSONB,
    observaciones         TEXT,
    CONSTRAINT ck_especificacion_espesor_objeto CHECK (
        espesor IS NULL OR jsonb_typeof(espesor) = 'object'
    ),
    CONSTRAINT ck_especificacion_dimensiones_objeto CHECK (
        dimensiones IS NULL OR jsonb_typeof(dimensiones) = 'object'
    ),
    CONSTRAINT ck_especificacion_accesorios_array CHECK (
        accesorios IS NULL OR jsonb_typeof(accesorios) = 'array'
    )
);

-- ============================================================================
-- 5. PEDIDOS
-- ============================================================================

CREATE TABLE pedidos (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proforma_id         BIGINT NOT NULL UNIQUE REFERENCES proformas(id),
    fecha_confirmacion  TIMESTAMPTZ,
    estado_id           BIGINT NOT NULL REFERENCES catalogo_valores(id),
    created_by_id       BIGINT,
    updated_by_id       BIGINT
);

CREATE INDEX ix_pedidos_estado ON pedidos(estado_id);
CREATE INDEX ix_pedidos_fecha_confirmacion ON pedidos(fecha_confirmacion);

-- Configuracion explicita de las transiciones permitidas del pedido.
CREATE TABLE transiciones_estado_pedido (
    estado_origen_id   BIGINT NOT NULL REFERENCES catalogo_valores(id),
    estado_destino_id  BIGINT NOT NULL REFERENCES catalogo_valores(id),
    PRIMARY KEY (estado_origen_id, estado_destino_id),
    CONSTRAINT ck_transicion_estados_distintos CHECK (estado_origen_id <> estado_destino_id)
);

-- ============================================================================
-- 6. ORDENES DE TRABAJO
-- ============================================================================

CREATE TABLE ordenes_trabajo (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id               BIGINT NOT NULL UNIQUE REFERENCES pedidos(id),
    jefe_taller_id          BIGINT NOT NULL,
    numero                  BIGINT NOT NULL UNIQUE,
    fecha                   DATE NOT NULL DEFAULT CURRENT_DATE,
    fecha_inicio            DATE,
    fecha_fin               DATE,
    responsable_recepcion   VARCHAR(200),
    fecha_entrega           DATE,
    lugar_entrega           TEXT,
    estado_saldo_id         BIGINT REFERENCES catalogo_valores(id),
    estado_id               BIGINT NOT NULL REFERENCES catalogo_valores(id),
    created_by_id           BIGINT,
    updated_by_id           BIGINT,
    CONSTRAINT ck_ot_fechas CHECK (fecha_fin IS NULL OR fecha_inicio IS NULL OR fecha_fin >= fecha_inicio)
);

CREATE INDEX ix_ot_pedido ON ordenes_trabajo(pedido_id);
CREATE INDEX ix_ot_jefe_taller ON ordenes_trabajo(jefe_taller_id);
CREATE INDEX ix_ot_estado ON ordenes_trabajo(estado_id);
CREATE INDEX ix_ot_estado_saldo ON ordenes_trabajo(estado_saldo_id);

-- ============================================================================
-- 7. NOTAS DE ENTREGA
-- ============================================================================

CREATE TABLE notas_entrega (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id       BIGINT NOT NULL UNIQUE REFERENCES pedidos(id),
    vendedor_id     BIGINT NOT NULL,
    numero          BIGINT NOT NULL UNIQUE,
    fecha           DATE NOT NULL DEFAULT CURRENT_DATE,
    created_by_id   BIGINT,
    updated_by_id   BIGINT
);

CREATE INDEX ix_notas_entrega_pedido ON notas_entrega(pedido_id);
CREATE INDEX ix_notas_entrega_vendedor ON notas_entrega(vendedor_id);
CREATE INDEX ix_notas_entrega_fecha ON notas_entrega(fecha);

-- ============================================================================
-- 8. RECIBOS DIGITALES (SE GUARDAN DATOS, NO EL DOCUMENTO GENERADO)
-- ============================================================================

CREATE TABLE recibos (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero           BIGINT NOT NULL UNIQUE,
    proforma_id      BIGINT NOT NULL REFERENCES proformas(id),
    nombre_completo  VARCHAR(250) NOT NULL,
    monto_en_letras  TEXT NOT NULL,
    concepto         TEXT NOT NULL,
    tipo_pago_id     BIGINT NOT NULL REFERENCES catalogo_valores(id),
    numero_cheque    VARCHAR(80),
    banco            VARCHAR(150),
    total            NUMERIC(14,2) NOT NULL,
    a_cuenta         NUMERIC(14,2),
    saldo            NUMERIC(14,2),
    fecha            DATE NOT NULL DEFAULT CURRENT_DATE,
    created_by_id    BIGINT,
    updated_by_id    BIGINT,
    CONSTRAINT ck_recibo_total_positive CHECK (total > 0),
    CONSTRAINT ck_recibo_a_cuenta_nonnegative CHECK (a_cuenta IS NULL OR a_cuenta >= 0),
    CONSTRAINT ck_recibo_saldo_nonnegative CHECK (saldo IS NULL OR saldo >= 0)
);

CREATE INDEX ix_recibos_proforma ON recibos(proforma_id);
CREATE INDEX ix_recibos_fecha ON recibos(fecha);
CREATE INDEX ix_recibos_tipo_pago ON recibos(tipo_pago_id);

-- La moneda del recibo NO se almacena: se obtiene siempre desde proformas.moneda_id.

-- ============================================================================
-- 9. ARCHIVOS ADJUNTOS
-- ============================================================================

CREATE TABLE archivos_adjuntos (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proforma_id     BIGINT NOT NULL REFERENCES proformas(id) ON DELETE RESTRICT,
    nombre          VARCHAR(255) NOT NULL,
    nombre_storage  VARCHAR(255) NOT NULL,
    ruta_storage    TEXT NOT NULL,
    mime_type       VARCHAR(150),
    tamano_bytes    BIGINT,
    created_by_id   BIGINT,
    updated_by_id   BIGINT,
    CONSTRAINT ck_archivo_tamano_nonnegative CHECK (tamano_bytes IS NULL OR tamano_bytes >= 0)
);

CREATE INDEX ix_archivos_proforma ON archivos_adjuntos(proforma_id);

-- ============================================================================
-- 10. CAPTURAS NLP / HITL
-- ============================================================================

CREATE TABLE capturas (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proforma_id         BIGINT NOT NULL REFERENCES proformas(id),
    proforma_detalle_id BIGINT REFERENCES proformas_detalle(id),
    vendedor_id         BIGINT NOT NULL,
    capturado_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    texto_transcrito    TEXT,
    texto_normalizado   TEXT,
    modelo_version      VARCHAR(255),
    latencia_total_ms   INTEGER,
    latencia_asr_ms     INTEGER,
    latencia_nlp_ms     INTEGER,
    num_items_ia        INTEGER NOT NULL DEFAULT 0,
    labels_detectados   JSONB,
    resultado_ia        JSONB,
    created_by_id       BIGINT,
    updated_by_id       BIGINT,
    CONSTRAINT ck_captura_latencias CHECK (
        (latencia_total_ms IS NULL OR latencia_total_ms >= 0)
        AND (latencia_asr_ms IS NULL OR latencia_asr_ms >= 0)
        AND (latencia_nlp_ms IS NULL OR latencia_nlp_ms >= 0)
    ),
    CONSTRAINT ck_captura_items_nonnegative CHECK (num_items_ia >= 0),
    CONSTRAINT ck_captura_labels_array CHECK (
        labels_detectados IS NULL OR jsonb_typeof(labels_detectados) = 'array'
    ),
    CONSTRAINT ck_captura_resultado_objeto CHECK (
        resultado_ia IS NULL OR jsonb_typeof(resultado_ia) = 'object'
    )
);

CREATE INDEX ix_capturas_proforma ON capturas(proforma_id);
CREATE INDEX ix_capturas_detalle ON capturas(proforma_detalle_id);
CREATE INDEX ix_capturas_vendedor ON capturas(vendedor_id);
CREATE INDEX ix_capturas_fecha ON capturas(capturado_at);

CREATE TABLE items_ia (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    captura_id          BIGINT NOT NULL UNIQUE REFERENCES capturas(id) ON DELETE CASCADE,
    nombre              VARCHAR(250) NOT NULL,
    espesor             JSONB,
    color_principal     VARCHAR(150),
    color_secundario    VARCHAR(150),
    dimensiones         JSONB,
    accesorios          JSONB,
    cantidad            NUMERIC(12,3),
    precio_total        NUMERIC(14,2),
    observaciones       TEXT,
    CONSTRAINT ck_item_ia_espesor_objeto CHECK (
        espesor IS NULL OR jsonb_typeof(espesor) = 'object'
    ),
    CONSTRAINT ck_item_ia_dimensiones_objeto CHECK (
        dimensiones IS NULL OR jsonb_typeof(dimensiones) = 'object'
    ),
    CONSTRAINT ck_item_ia_accesorios_array CHECK (
        accesorios IS NULL OR jsonb_typeof(accesorios) = 'array'
    ),
    CONSTRAINT ck_item_ia_cantidad_positive CHECK (cantidad IS NULL OR cantidad > 0),
    CONSTRAINT ck_item_ia_precio_nonnegative CHECK (precio_total IS NULL OR precio_total >= 0)
);

CREATE TABLE items_humano (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    captura_id          BIGINT NOT NULL UNIQUE REFERENCES capturas(id) ON DELETE CASCADE,
    item_ia_id          BIGINT UNIQUE REFERENCES items_ia(id) ON DELETE SET NULL,
    nombre              VARCHAR(250) NOT NULL,
    espesor             JSONB,
    color_principal     VARCHAR(150),
    color_secundario    VARCHAR(150),
    dimensiones         JSONB,
    accesorios          JSONB,
    cantidad            NUMERIC(12,3),
    precio_total        NUMERIC(14,2),
    observaciones       TEXT,
    campos_totales      INTEGER NOT NULL DEFAULT 0,
    campos_corregidos   INTEGER NOT NULL DEFAULT 0,
    campos_agregados    INTEGER NOT NULL DEFAULT 0,
    campos_eliminados   INTEGER NOT NULL DEFAULT 0,
    precision_item      NUMERIC(6,5),
    precision_campo     NUMERIC(6,5),
    revisor_id          BIGINT,
    revisado_at         TIMESTAMPTZ,
    created_by_id       BIGINT,
    updated_by_id       BIGINT,
    CONSTRAINT ck_item_humano_espesor_objeto CHECK (
        espesor IS NULL OR jsonb_typeof(espesor) = 'object'
    ),
    CONSTRAINT ck_item_humano_dimensiones_objeto CHECK (
        dimensiones IS NULL OR jsonb_typeof(dimensiones) = 'object'
    ),
    CONSTRAINT ck_item_humano_accesorios_array CHECK (
        accesorios IS NULL OR jsonb_typeof(accesorios) = 'array'
    ),
    CONSTRAINT ck_item_humano_cantidad_positive CHECK (cantidad IS NULL OR cantidad > 0),
    CONSTRAINT ck_item_humano_precio_nonnegative CHECK (precio_total IS NULL OR precio_total >= 0),
    CONSTRAINT ck_item_humano_metricas_counts CHECK (
        campos_totales >= 0
        AND campos_corregidos >= 0
        AND campos_agregados >= 0
        AND campos_eliminados >= 0
        AND campos_corregidos <= campos_totales
    ),
    CONSTRAINT ck_item_humano_precision_range CHECK (
        (precision_item IS NULL OR (precision_item >= 0 AND precision_item <= 1))
        AND (precision_campo IS NULL OR (precision_campo >= 0 AND precision_campo <= 1))
    )
);

CREATE INDEX ix_items_humano_revisor ON items_humano(revisor_id);

CREATE TABLE evaluaciones_nlp (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    captura_id              BIGINT NOT NULL UNIQUE REFERENCES capturas(id) ON DELETE CASCADE,
    inicio_revision_at      TIMESTAMPTZ,
    fin_revision_at         TIMESTAMPTZ,
    tiempo_revision_ms      INTEGER,
    num_items_ia            INTEGER NOT NULL DEFAULT 0,
    num_items_humano        INTEGER NOT NULL DEFAULT 0,
    campos_totales_captura  INTEGER NOT NULL DEFAULT 0,
    campos_corregidos_total INTEGER NOT NULL DEFAULT 0,
    campos_agregados_total  INTEGER NOT NULL DEFAULT 0,
    campos_eliminados_total INTEGER NOT NULL DEFAULT 0,
    precision_global        NUMERIC(6,5),
    evaluated_by_id         BIGINT,
    CONSTRAINT ck_eval_tiempo CHECK (tiempo_revision_ms IS NULL OR tiempo_revision_ms >= 0),
    CONSTRAINT ck_eval_intervalo CHECK (
        fin_revision_at IS NULL OR inicio_revision_at IS NULL OR fin_revision_at >= inicio_revision_at
    ),
    CONSTRAINT ck_eval_counts CHECK (
        num_items_ia >= 0
        AND num_items_humano >= 0
        AND campos_totales_captura >= 0
        AND campos_corregidos_total >= 0
        AND campos_agregados_total >= 0
        AND campos_eliminados_total >= 0
        AND campos_corregidos_total <= campos_totales_captura
    ),
    CONSTRAINT ck_eval_precision CHECK (
        precision_global IS NULL OR (precision_global >= 0 AND precision_global <= 1)
    )
);

-- ============================================================================
-- 11. MEDICIONES DEL PROCESO (MANUAL VS NLP + HITL)
-- ============================================================================

CREATE TABLE mediciones_proceso (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proforma_id     BIGINT NOT NULL REFERENCES proformas(id),
    metodo_id       BIGINT NOT NULL REFERENCES catalogo_valores(id),
    inicio_at       TIMESTAMPTZ NOT NULL,
    fin_at          TIMESTAMPTZ NOT NULL,
    tiempo_total_ms INTEGER NOT NULL,
    num_items       INTEGER NOT NULL DEFAULT 1,
    observaciones   TEXT,
    created_by_id   BIGINT,
    updated_by_id   BIGINT,
    CONSTRAINT ck_medicion_intervalo CHECK (fin_at >= inicio_at),
    CONSTRAINT ck_medicion_tiempo CHECK (tiempo_total_ms >= 0),
    CONSTRAINT ck_medicion_items CHECK (num_items > 0)
);

CREATE INDEX ix_mediciones_proforma ON mediciones_proceso(proforma_id);
CREATE INDEX ix_mediciones_metodo ON mediciones_proceso(metodo_id);

-- ============================================================================
-- 12. MOVIMIENTOS DE STOCK
-- ============================================================================

CREATE TABLE movimientos_stock (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id         BIGINT NOT NULL REFERENCES productos(id),
    fecha               TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    tipo_movimiento_id  BIGINT NOT NULL REFERENCES catalogo_valores(id),
    cantidad            NUMERIC(12,3) NOT NULL,
    pedido_id           BIGINT REFERENCES pedidos(id),
    observaciones       TEXT,
    created_by_id       BIGINT,
    CONSTRAINT ck_mov_stock_cantidad_nonzero CHECK (cantidad <> 0)
);

CREATE INDEX ix_mov_stock_producto ON movimientos_stock(producto_id);
CREATE INDEX ix_mov_stock_fecha ON movimientos_stock(fecha);
CREATE INDEX ix_mov_stock_pedido ON movimientos_stock(pedido_id);
CREATE INDEX ix_mov_stock_tipo ON movimientos_stock(tipo_movimiento_id);

-- Una VENTA por producto y pedido. Si el mismo producto aparece en varias lineas
-- de la proforma, la cantidad se agrega antes de generar la salida.
CREATE UNIQUE INDEX uq_mov_stock_venta_pedido_producto
    ON movimientos_stock(pedido_id, producto_id)
    WHERE pedido_id IS NOT NULL;

-- ============================================================================
-- 13. DATOS INICIALES DE CATALOGOS
-- ============================================================================

INSERT INTO catalogo_conceptos (codigo, descripcion, activo)
VALUES
    ('TIPO_CLIENTE',         'Clasificacion del cliente registrado en HOMEX.', TRUE),
    ('TIPO_ITEM',            'Tipo de elemento que puede aparecer en una proforma.', TRUE),
    ('ESTADO_PROFORMA',      'Estados del ciclo de vida de una proforma.', TRUE),
    ('ESTADO_PEDIDO',        'Estados del ciclo de vida del pedido.', TRUE),
    ('ESTADO_ORDEN_TRABAJO', 'Estados del proceso de una orden de trabajo.', TRUE),
    ('ESTADO_SALDO',         'Estado del saldo mostrado en la orden de trabajo.', TRUE),
    ('MONEDA',               'Monedas en las que HOMEX cotiza y recibe pagos.', TRUE),
    ('UNIDAD_MEDIDA',        'Unidades de comercializacion y existencia.', TRUE),
    ('TIPO_PAGO',            'Formas de pago contempladas en el recibo.', TRUE),
    ('TIPO_MOVIMIENTO',      'Clasificacion de los movimientos que afectan stock.', TRUE),
    ('CATEGORIA_PRODUCTO',   'Clasificacion general de productos maestros.', TRUE),
    ('TIPO_MUEBLE',          'Tipos principales de muebles a medida.', TRUE),
    ('MARCA',                'Marcas de productos de catalogo.', TRUE),
    ('COLOR',                'Colores de productos de catalogo.', TRUE),
    ('TIPO_PISO',            'Tipos de piso flotante comercializados por HOMEX.', TRUE),
    ('MATERIAL_PISO',        'Materiales de los pisos flotantes.', TRUE),
    ('DISENO_PISO',          'Disenos de los pisos flotantes.', TRUE),
    ('ACABADO_PISO',         'Acabados de los pisos flotantes.', TRUE),
    ('METODO_PROCESO',       'Metodo utilizado para medir la elaboracion de una cotizacion.', TRUE)
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO catalogo_valores (concepto_id, codigo, nombre, activo)
SELECT c.id, v.codigo, v.nombre, TRUE
FROM catalogo_conceptos c
CROSS JOIN (VALUES
    ('PERSONA', 'Persona natural'),
    ('EMPRESA', 'Empresa')
) AS v(codigo, nombre)
WHERE c.codigo = 'TIPO_CLIENTE'
ON CONFLICT (concepto_id, codigo) DO NOTHING;

INSERT INTO catalogo_valores (concepto_id, codigo, nombre, activo)
SELECT c.id, v.codigo, v.nombre, TRUE
FROM catalogo_conceptos c
CROSS JOIN (VALUES
    ('MUEBLE_MEDIDA', 'Mueble a medida'),
    ('SILLA',         'Silla de oficina'),
    ('PISO_FLOTANTE', 'Piso flotante'),
    ('OTRO',          'Otro producto')
) AS v(codigo, nombre)
WHERE c.codigo = 'TIPO_ITEM'
ON CONFLICT (concepto_id, codigo) DO NOTHING;

INSERT INTO catalogo_valores (concepto_id, codigo, nombre, activo)
SELECT c.id, v.codigo, v.nombre, TRUE
FROM catalogo_conceptos c
CROSS JOIN (VALUES
    ('BORRADOR',  'Borrador'),
    ('ENVIADA',   'Enviada'),
    ('APROBADA',  'Aprobada'),
    ('RECHAZADA', 'Rechazada'),
    ('VENCIDA',   'Vencida'),
    ('ANULADA',   'Anulada')
) AS v(codigo, nombre)
WHERE c.codigo = 'ESTADO_PROFORMA'
ON CONFLICT (concepto_id, codigo) DO NOTHING;

INSERT INTO catalogo_valores (concepto_id, codigo, nombre, activo)
SELECT c.id, v.codigo, v.nombre, TRUE
FROM catalogo_conceptos c
CROSS JOIN (VALUES
    ('CONFIRMADO',    'Confirmado'),
    ('EN_PRODUCCION', 'En produccion'),
    ('LISTO_ENTREGA', 'Listo para entrega'),
    ('ENTREGADO',     'Entregado'),
    ('CANCELADO',     'Cancelado')
) AS v(codigo, nombre)
WHERE c.codigo = 'ESTADO_PEDIDO'
ON CONFLICT (concepto_id, codigo) DO NOTHING;

INSERT INTO catalogo_valores (concepto_id, codigo, nombre, activo)
SELECT c.id, v.codigo, v.nombre, TRUE
FROM catalogo_conceptos c
CROSS JOIN (VALUES
    ('PENDIENTE',  'Pendiente'),
    ('EN_PROCESO', 'En proceso'),
    ('TERMINADA',  'Terminada'),
    ('CANCELADA',  'Cancelada')
) AS v(codigo, nombre)
WHERE c.codigo = 'ESTADO_ORDEN_TRABAJO'
ON CONFLICT (concepto_id, codigo) DO NOTHING;

INSERT INTO catalogo_valores (concepto_id, codigo, nombre, activo)
SELECT c.id, v.codigo, v.nombre, TRUE
FROM catalogo_conceptos c
CROSS JOIN (VALUES
    ('PENDIENTE', 'Pendiente'),
    ('PARCIAL',   'Parcial'),
    ('PAGADO',    'Pagado')
) AS v(codigo, nombre)
WHERE c.codigo = 'ESTADO_SALDO'
ON CONFLICT (concepto_id, codigo) DO NOTHING;

INSERT INTO catalogo_valores (concepto_id, codigo, nombre, activo)
SELECT c.id, v.codigo, v.nombre, TRUE
FROM catalogo_conceptos c
CROSS JOIN (VALUES
    ('BOB', 'Bolivianos'),
    ('USD', 'Dolares estadounidenses')
) AS v(codigo, nombre)
WHERE c.codigo = 'MONEDA'
ON CONFLICT (concepto_id, codigo) DO NOTHING;

-- Solo PIEZA y CAJA son unidades transaccionales. Los m2 de piso se derivan de
-- productos_piso.m2_por_caja y no se usan para descontar stock.
INSERT INTO catalogo_valores (concepto_id, codigo, nombre, activo)
SELECT c.id, v.codigo, v.nombre, TRUE
FROM catalogo_conceptos c
CROSS JOIN (VALUES
    ('PIEZA', 'Pieza'),
    ('CAJA',  'Caja')
) AS v(codigo, nombre)
WHERE c.codigo = 'UNIDAD_MEDIDA'
ON CONFLICT (concepto_id, codigo) DO NOTHING;

INSERT INTO catalogo_valores (concepto_id, codigo, nombre, activo)
SELECT c.id, v.codigo, v.nombre, TRUE
FROM catalogo_conceptos c
CROSS JOIN (VALUES
    ('EFECTIVO', 'Efectivo'),
    ('CHEQUE',   'Cheque')
) AS v(codigo, nombre)
WHERE c.codigo = 'TIPO_PAGO'
ON CONFLICT (concepto_id, codigo) DO NOTHING;

INSERT INTO catalogo_valores (concepto_id, codigo, nombre, activo)
SELECT c.id, v.codigo, v.nombre, TRUE
FROM catalogo_conceptos c
CROSS JOIN (VALUES
    ('VENTA',         'Salida por venta de producto asociada a pedido confirmado'),
    ('CARGA_INICIAL', 'Carga inicial de existencias'),
    ('AJUSTE',        'Ajuste de stock; admite cantidad positiva o negativa')
) AS v(codigo, nombre)
WHERE c.codigo = 'TIPO_MOVIMIENTO'
ON CONFLICT (concepto_id, codigo) DO NOTHING;

INSERT INTO catalogo_valores (concepto_id, codigo, nombre, activo)
SELECT c.id, v.codigo, v.nombre, TRUE
FROM catalogo_conceptos c
CROSS JOIN (VALUES
    ('SILLA',         'Silla'),
    ('PISO_FLOTANTE', 'Piso flotante'),
    ('OTRO',          'Otro producto')
) AS v(codigo, nombre)
WHERE c.codigo = 'CATEGORIA_PRODUCTO'
ON CONFLICT (concepto_id, codigo) DO NOTHING;

INSERT INTO catalogo_valores (concepto_id, codigo, nombre, activo)
SELECT c.id, v.codigo, v.nombre, TRUE
FROM catalogo_conceptos c
CROSS JOIN (VALUES
    ('MESA_REUNION', 'Mesa de reunion'),
    ('ESTANTE',      'Estante'),
    ('ESCRITORIO',   'Escritorio'),
    ('CREDENZA',     'Credenza'),
    ('ARCHIVERO',    'Archivero'),
    ('GAVETERO',     'Gavetero')
) AS v(codigo, nombre)
WHERE c.codigo = 'TIPO_MUEBLE'
ON CONFLICT (concepto_id, codigo) DO NOTHING;

INSERT INTO catalogo_valores (concepto_id, codigo, nombre, activo)
SELECT c.id, v.codigo, v.nombre, TRUE
FROM catalogo_conceptos c
CROSS JOIN (VALUES
    ('MANUAL',   'Proceso tradicional/manual'),
    ('NLP_HITL', 'Proceso asistido por NLP con intervencion humana')
) AS v(codigo, nombre)
WHERE c.codigo = 'METODO_PROCESO'
ON CONFLICT (concepto_id, codigo) DO NOTHING;

-- Colores observados en el catalogo de sillas suministrado por HOMEX.
INSERT INTO catalogo_valores (concepto_id, codigo, nombre, activo)
SELECT c.id, v.codigo, v.nombre, TRUE
FROM catalogo_conceptos c
CROSS JOIN (VALUES
    ('NEGRO',       'Negro'),
    ('TURQUESA',    'Turquesa'),
    ('CELESTE',     'Celeste'),
    ('GRIS',        'Gris'),
    ('GUINDO',      'Guindo'),
    ('PLOMO',       'Plomo'),
    ('AMARILLO',    'Amarillo'),
    ('AZUL',        'Azul'),
    ('CAFE',        'Cafe'),
    ('CAFE_OSCURO', 'Cafe oscuro')
) AS v(codigo, nombre)
WHERE c.codigo = 'COLOR'
ON CONFLICT (concepto_id, codigo) DO NOTHING;

-- Los conceptos TIPO_PISO, MATERIAL_PISO, DISENO_PISO y ACABADO_PISO se crean
-- desde el inicio, pero NO se inventan valores. Se cargaran con el catalogo real.

-- Transiciones actualmente permitidas para PEDIDOS.
INSERT INTO transiciones_estado_pedido (estado_origen_id, estado_destino_id)
SELECT origen.id, destino.id
FROM catalogo_valores origen
JOIN catalogo_conceptos co ON co.id = origen.concepto_id AND co.codigo = 'ESTADO_PEDIDO'
JOIN catalogo_valores destino ON destino.concepto_id = origen.concepto_id
WHERE (origen.codigo, destino.codigo) IN (
    ('CONFIRMADO', 'EN_PRODUCCION'),
    ('EN_PRODUCCION', 'LISTO_ENTREGA'),
    ('LISTO_ENTREGA', 'ENTREGADO')
)
ON CONFLICT DO NOTHING;

-- ============================================================================
-- 14. FUNCIONES AUXILIARES PARA CATALOGO UNIVERSAL
-- ============================================================================

CREATE OR REPLACE FUNCTION fn_catalogo_valor_pertenece(
    p_valor_id BIGINT,
    p_concepto_codigo VARCHAR
) RETURNS BOOLEAN
LANGUAGE SQL
STABLE
AS $$
    SELECT EXISTS (
        SELECT 1
          FROM catalogo_valores cv
          JOIN catalogo_conceptos cc ON cc.id = cv.concepto_id
         WHERE cv.id = p_valor_id
           AND cc.codigo = p_concepto_codigo
           AND cc.activo = TRUE
           AND cv.activo = TRUE
    );
$$;

CREATE OR REPLACE FUNCTION fn_catalogo_valor_es(
    p_valor_id BIGINT,
    p_concepto_codigo VARCHAR,
    p_valor_codigo VARCHAR
) RETURNS BOOLEAN
LANGUAGE SQL
STABLE
AS $$
    SELECT EXISTS (
        SELECT 1
          FROM catalogo_valores cv
          JOIN catalogo_conceptos cc ON cc.id = cv.concepto_id
         WHERE cv.id = p_valor_id
           AND cc.codigo = p_concepto_codigo
           AND cv.codigo = p_valor_codigo
           AND cc.activo = TRUE
           AND cv.activo = TRUE
    );
$$;

CREATE OR REPLACE FUNCTION fn_catalogo_codigo_valor(
    p_valor_id BIGINT,
    p_concepto_codigo VARCHAR
) RETURNS TEXT
LANGUAGE SQL
STABLE
AS $$
    SELECT cv.codigo
      FROM catalogo_valores cv
      JOIN catalogo_conceptos cc ON cc.id = cv.concepto_id
     WHERE cv.id = p_valor_id
       AND cc.codigo = p_concepto_codigo
       AND cc.activo = TRUE
       AND cv.activo = TRUE;
$$;

-- ============================================================================
-- 15. VALIDACIONES DE CLIENTES Y CATALOGOS
-- ============================================================================

CREATE OR REPLACE FUNCTION fn_validar_cliente()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF NOT fn_catalogo_valor_pertenece(NEW.tipo_cliente_id, 'TIPO_CLIENTE') THEN
        RAISE EXCEPTION 'tipo_cliente_id % no pertenece a TIPO_CLIENTE activo', NEW.tipo_cliente_id;
    END IF;

    IF fn_catalogo_valor_es(NEW.tipo_cliente_id, 'TIPO_CLIENTE', 'EMPRESA') THEN
        IF NULLIF(BTRIM(NEW.empresa), '') IS NULL THEN
            RAISE EXCEPTION 'Un cliente EMPRESA debe registrar el nombre de la empresa';
        END IF;
        IF NULLIF(BTRIM(NEW.nombres), '') IS NULL THEN
            RAISE EXCEPTION 'Un cliente EMPRESA debe registrar los nombres de la persona de contacto';
        END IF;
        IF NULLIF(BTRIM(NEW.apellidos), '') IS NULL THEN
            RAISE EXCEPTION 'Un cliente EMPRESA debe registrar los apellidos de la persona de contacto';
        END IF;
    ELSIF fn_catalogo_valor_es(NEW.tipo_cliente_id, 'TIPO_CLIENTE', 'PERSONA') THEN
        IF NULLIF(BTRIM(NEW.nombres), '') IS NULL THEN
            RAISE EXCEPTION 'Un cliente PERSONA debe registrar nombres';
        END IF;
        IF NULLIF(BTRIM(NEW.apellidos), '') IS NULL THEN
            RAISE EXCEPTION 'Un cliente PERSONA debe registrar apellidos';
        END IF;
        IF NULLIF(BTRIM(NEW.empresa), '') IS NOT NULL THEN
            RAISE EXCEPTION 'Un cliente PERSONA no debe registrar empresa';
        END IF;
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_validar_cliente
BEFORE INSERT OR UPDATE ON clientes
FOR EACH ROW
EXECUTE FUNCTION fn_validar_cliente();

CREATE OR REPLACE FUNCTION fn_validar_producto_catalogos()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_categoria TEXT;
    v_unidad TEXT;
BEGIN
    IF NOT fn_catalogo_valor_pertenece(NEW.categoria_id, 'CATEGORIA_PRODUCTO') THEN
        RAISE EXCEPTION 'categoria_id % no pertenece a CATEGORIA_PRODUCTO activo', NEW.categoria_id;
    END IF;
    IF NOT fn_catalogo_valor_pertenece(NEW.unidad_stock_id, 'UNIDAD_MEDIDA') THEN
        RAISE EXCEPTION 'unidad_stock_id % no pertenece a UNIDAD_MEDIDA activa', NEW.unidad_stock_id;
    END IF;

    v_categoria := fn_catalogo_codigo_valor(NEW.categoria_id, 'CATEGORIA_PRODUCTO');
    v_unidad := fn_catalogo_codigo_valor(NEW.unidad_stock_id, 'UNIDAD_MEDIDA');

    IF v_categoria = 'PISO_FLOTANTE' AND v_unidad <> 'CAJA' THEN
        RAISE EXCEPTION 'Un producto PISO_FLOTANTE debe manejar stock exclusivamente en CAJA';
    ELSIF v_categoria IN ('SILLA', 'OTRO') AND v_unidad <> 'PIEZA' THEN
        RAISE EXCEPTION 'Los productos de categoria % deben manejar stock en PIEZA', v_categoria;
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_validar_producto_catalogos
BEFORE INSERT OR UPDATE OF categoria_id, unidad_stock_id ON productos
FOR EACH ROW
EXECUTE FUNCTION fn_validar_producto_catalogos();

CREATE OR REPLACE FUNCTION fn_validar_producto_silla()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_categoria TEXT;
BEGIN
    SELECT fn_catalogo_codigo_valor(p.categoria_id, 'CATEGORIA_PRODUCTO')
      INTO v_categoria
      FROM productos p
     WHERE p.id = NEW.producto_id;

    IF v_categoria IS DISTINCT FROM 'SILLA' THEN
        RAISE EXCEPTION 'productos_silla solo puede asociarse a un producto de categoria SILLA';
    END IF;

    IF NEW.marca_id IS NOT NULL AND NOT fn_catalogo_valor_pertenece(NEW.marca_id, 'MARCA') THEN
        RAISE EXCEPTION 'marca_id % no pertenece a MARCA activa', NEW.marca_id;
    END IF;
    IF NEW.color_primario_id IS NOT NULL AND NOT fn_catalogo_valor_pertenece(NEW.color_primario_id, 'COLOR') THEN
        RAISE EXCEPTION 'color_primario_id % no pertenece a COLOR activo', NEW.color_primario_id;
    END IF;
    IF NEW.color_secundario_id IS NOT NULL AND NOT fn_catalogo_valor_pertenece(NEW.color_secundario_id, 'COLOR') THEN
        RAISE EXCEPTION 'color_secundario_id % no pertenece a COLOR activo', NEW.color_secundario_id;
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_validar_producto_silla
BEFORE INSERT OR UPDATE ON productos_silla
FOR EACH ROW
EXECUTE FUNCTION fn_validar_producto_silla();

CREATE OR REPLACE FUNCTION fn_validar_producto_piso()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_categoria TEXT;
    v_unidad TEXT;
BEGIN
    SELECT fn_catalogo_codigo_valor(p.categoria_id, 'CATEGORIA_PRODUCTO'),
           fn_catalogo_codigo_valor(p.unidad_stock_id, 'UNIDAD_MEDIDA')
      INTO v_categoria, v_unidad
      FROM productos p
     WHERE p.id = NEW.producto_id;

    IF v_categoria IS DISTINCT FROM 'PISO_FLOTANTE' THEN
        RAISE EXCEPTION 'productos_piso solo puede asociarse a un producto de categoria PISO_FLOTANTE';
    END IF;
    IF v_unidad IS DISTINCT FROM 'CAJA' THEN
        RAISE EXCEPTION 'Todo piso debe manejar stock en CAJA';
    END IF;

    IF NEW.marca_id IS NOT NULL AND NOT fn_catalogo_valor_pertenece(NEW.marca_id, 'MARCA') THEN
        RAISE EXCEPTION 'marca_id % no pertenece a MARCA activa', NEW.marca_id;
    END IF;
    IF NEW.tipo_id IS NOT NULL AND NOT fn_catalogo_valor_pertenece(NEW.tipo_id, 'TIPO_PISO') THEN
        RAISE EXCEPTION 'tipo_id % no pertenece a TIPO_PISO activo', NEW.tipo_id;
    END IF;
    IF NEW.material_id IS NOT NULL AND NOT fn_catalogo_valor_pertenece(NEW.material_id, 'MATERIAL_PISO') THEN
        RAISE EXCEPTION 'material_id % no pertenece a MATERIAL_PISO activo', NEW.material_id;
    END IF;
    IF NEW.diseno_id IS NOT NULL AND NOT fn_catalogo_valor_pertenece(NEW.diseno_id, 'DISENO_PISO') THEN
        RAISE EXCEPTION 'diseno_id % no pertenece a DISENO_PISO activo', NEW.diseno_id;
    END IF;
    IF NEW.acabado_id IS NOT NULL AND NOT fn_catalogo_valor_pertenece(NEW.acabado_id, 'ACABADO_PISO') THEN
        RAISE EXCEPTION 'acabado_id % no pertenece a ACABADO_PISO activo', NEW.acabado_id;
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_validar_producto_piso
BEFORE INSERT OR UPDATE ON productos_piso
FOR EACH ROW
EXECUTE FUNCTION fn_validar_producto_piso();

CREATE OR REPLACE FUNCTION fn_validar_proforma_catalogos()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF NOT fn_catalogo_valor_pertenece(NEW.estado_id, 'ESTADO_PROFORMA') THEN
        RAISE EXCEPTION 'estado_id % no pertenece a ESTADO_PROFORMA activo', NEW.estado_id;
    END IF;
    IF NOT fn_catalogo_valor_pertenece(NEW.moneda_id, 'MONEDA') THEN
        RAISE EXCEPTION 'moneda_id % no pertenece a MONEDA activa', NEW.moneda_id;
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_validar_proforma_catalogos
BEFORE INSERT OR UPDATE OF estado_id, moneda_id ON proformas
FOR EACH ROW
EXECUTE FUNCTION fn_validar_proforma_catalogos();

CREATE OR REPLACE FUNCTION fn_validar_orden_trabajo_catalogos()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF NOT fn_catalogo_valor_pertenece(NEW.estado_id, 'ESTADO_ORDEN_TRABAJO') THEN
        RAISE EXCEPTION 'estado_id % no pertenece a ESTADO_ORDEN_TRABAJO activo', NEW.estado_id;
    END IF;
    IF NEW.estado_saldo_id IS NOT NULL
       AND NOT fn_catalogo_valor_pertenece(NEW.estado_saldo_id, 'ESTADO_SALDO') THEN
        RAISE EXCEPTION 'estado_saldo_id % no pertenece a ESTADO_SALDO activo', NEW.estado_saldo_id;
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_validar_orden_trabajo_catalogos
BEFORE INSERT OR UPDATE OF estado_id, estado_saldo_id ON ordenes_trabajo
FOR EACH ROW
EXECUTE FUNCTION fn_validar_orden_trabajo_catalogos();

CREATE OR REPLACE FUNCTION fn_validar_medicion_metodo()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF NOT fn_catalogo_valor_pertenece(NEW.metodo_id, 'METODO_PROCESO') THEN
        RAISE EXCEPTION 'metodo_id % no pertenece a METODO_PROCESO activo', NEW.metodo_id;
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_validar_medicion_metodo
BEFORE INSERT OR UPDATE OF metodo_id ON mediciones_proceso
FOR EACH ROW
EXECUTE FUNCTION fn_validar_medicion_metodo();

-- ============================================================================
-- 16. VALIDACION DE DETALLES Y ESPECIFICACIONES DE MUEBLES
-- ============================================================================

CREATE OR REPLACE FUNCTION fn_validar_proforma_detalle()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_tipo TEXT;
    v_categoria TEXT;
    v_unidad TEXT;
    v_unidad_producto BIGINT;
BEGIN
    IF NOT fn_catalogo_valor_pertenece(NEW.tipo_item_id, 'TIPO_ITEM') THEN
        RAISE EXCEPTION 'tipo_item_id % no pertenece a TIPO_ITEM activo', NEW.tipo_item_id;
    END IF;
    IF NOT fn_catalogo_valor_pertenece(NEW.unidad_id, 'UNIDAD_MEDIDA') THEN
        RAISE EXCEPTION 'unidad_id % no pertenece a UNIDAD_MEDIDA activa', NEW.unidad_id;
    END IF;

    v_tipo := fn_catalogo_codigo_valor(NEW.tipo_item_id, 'TIPO_ITEM');
    v_unidad := fn_catalogo_codigo_valor(NEW.unidad_id, 'UNIDAD_MEDIDA');

    IF v_tipo = 'MUEBLE_MEDIDA' THEN
        IF NEW.producto_id IS NOT NULL THEN
            RAISE EXCEPTION 'Un MUEBLE_MEDIDA no debe apuntar a PRODUCTOS';
        END IF;
        IF v_unidad <> 'PIEZA' THEN
            RAISE EXCEPTION 'Un MUEBLE_MEDIDA debe cotizarse en PIEZA';
        END IF;
    ELSE
        IF NEW.producto_id IS NULL THEN
            RAISE EXCEPTION 'El tipo de item % requiere producto_id', v_tipo;
        END IF;

        SELECT fn_catalogo_codigo_valor(p.categoria_id, 'CATEGORIA_PRODUCTO'), p.unidad_stock_id
          INTO v_categoria, v_unidad_producto
          FROM productos p
         WHERE p.id = NEW.producto_id
           AND p.activo = TRUE;

        IF v_categoria IS NULL THEN
            RAISE EXCEPTION 'Producto % no existe, esta inactivo o tiene una categoria invalida', NEW.producto_id;
        END IF;

        IF v_tipo = 'SILLA' AND v_categoria <> 'SILLA' THEN
            RAISE EXCEPTION 'El item SILLA debe utilizar un producto de categoria SILLA';
        ELSIF v_tipo = 'PISO_FLOTANTE' AND v_categoria <> 'PISO_FLOTANTE' THEN
            RAISE EXCEPTION 'El item PISO_FLOTANTE debe utilizar un producto de categoria PISO_FLOTANTE';
        ELSIF v_tipo = 'OTRO' AND v_categoria <> 'OTRO' THEN
            RAISE EXCEPTION 'El item OTRO debe utilizar un producto de categoria OTRO';
        END IF;

        IF v_tipo = 'SILLA' AND NOT EXISTS (SELECT 1 FROM productos_silla ps WHERE ps.producto_id = NEW.producto_id) THEN
            RAISE EXCEPTION 'El producto SILLA % no tiene su ficha en productos_silla', NEW.producto_id;
        ELSIF v_tipo = 'PISO_FLOTANTE' AND NOT EXISTS (SELECT 1 FROM productos_piso pp WHERE pp.producto_id = NEW.producto_id) THEN
            RAISE EXCEPTION 'El producto PISO_FLOTANTE % no tiene su ficha en productos_piso', NEW.producto_id;
        END IF;

        IF NEW.unidad_id <> v_unidad_producto THEN
            RAISE EXCEPTION 'La unidad de venta del producto debe coincidir con su unidad de stock';
        END IF;

        IF v_tipo = 'PISO_FLOTANTE' AND v_unidad <> 'CAJA' THEN
            RAISE EXCEPTION 'Los pisos se venden exclusivamente por CAJA';
        ELSIF v_tipo IN ('SILLA', 'OTRO') AND v_unidad <> 'PIEZA' THEN
            RAISE EXCEPTION 'Los items % se venden en PIEZA', v_tipo;
        END IF;
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_validar_proforma_detalle
BEFORE INSERT OR UPDATE ON proformas_detalle
FOR EACH ROW
EXECUTE FUNCTION fn_validar_proforma_detalle();

CREATE OR REPLACE FUNCTION fn_calcular_total_detalle_proforma()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_bruto NUMERIC(14,2);
BEGIN
    v_bruto := NEW.cantidad * NEW.precio_unitario;

    IF NEW.descuento > v_bruto THEN
        RAISE EXCEPTION 'El descuento % no puede ser mayor al importe bruto % del detalle', NEW.descuento, v_bruto;
    END IF;

    NEW.total := v_bruto - NEW.descuento;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_calcular_total_detalle_proforma
BEFORE INSERT OR UPDATE OF cantidad, precio_unitario, descuento ON proformas_detalle
FOR EACH ROW
EXECUTE FUNCTION fn_calcular_total_detalle_proforma();

CREATE OR REPLACE FUNCTION fn_validar_especificacion_mueble()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_tipo TEXT;
BEGIN
    SELECT fn_catalogo_codigo_valor(pd.tipo_item_id, 'TIPO_ITEM')
      INTO v_tipo
      FROM proformas_detalle pd
     WHERE pd.id = NEW.proforma_detalle_id;

    IF v_tipo IS DISTINCT FROM 'MUEBLE_MEDIDA' THEN
        RAISE EXCEPTION 'especificaciones_mueble solo puede asociarse a un detalle MUEBLE_MEDIDA';
    END IF;

    IF NEW.tipo_mueble_id IS NOT NULL
       AND NOT fn_catalogo_valor_pertenece(NEW.tipo_mueble_id, 'TIPO_MUEBLE') THEN
        RAISE EXCEPTION 'tipo_mueble_id % no pertenece a TIPO_MUEBLE activo', NEW.tipo_mueble_id;
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_validar_especificacion_mueble
BEFORE INSERT OR UPDATE ON especificaciones_mueble
FOR EACH ROW
EXECUTE FUNCTION fn_validar_especificacion_mueble();

-- Antes de ENVIAR o APROBAR una proforma, todo MUEBLE_MEDIDA debe tener su
-- registro de especificaciones. Esto evita documentos incompletos.
CREATE OR REPLACE FUNCTION fn_validar_proforma_lista_para_estado()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_nuevo_estado TEXT;
    v_faltantes INTEGER;
BEGIN
    IF NEW.estado_id IS NOT DISTINCT FROM OLD.estado_id THEN
        RETURN NEW;
    END IF;

    v_nuevo_estado := fn_catalogo_codigo_valor(NEW.estado_id, 'ESTADO_PROFORMA');

    IF v_nuevo_estado IN ('ENVIADA', 'APROBADA') THEN
        IF NOT EXISTS (SELECT 1 FROM proformas_detalle pd WHERE pd.proforma_id = NEW.id) THEN
            RAISE EXCEPTION 'La proforma % no puede pasar a % sin detalles', NEW.id, v_nuevo_estado;
        END IF;

        SELECT COUNT(*)
          INTO v_faltantes
          FROM proformas_detalle pd
         WHERE pd.proforma_id = NEW.id
           AND fn_catalogo_valor_es(pd.tipo_item_id, 'TIPO_ITEM', 'MUEBLE_MEDIDA')
           AND NOT EXISTS (
               SELECT 1
                 FROM especificaciones_mueble em
                WHERE em.proforma_detalle_id = pd.id
           );

        IF v_faltantes > 0 THEN
            RAISE EXCEPTION 'La proforma % contiene % mueble(s) a medida sin especificaciones', NEW.id, v_faltantes;
        END IF;
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_validar_proforma_lista_para_estado
BEFORE UPDATE OF estado_id ON proformas
FOR EACH ROW
EXECUTE FUNCTION fn_validar_proforma_lista_para_estado();

-- ============================================================================
-- 17. RECALCULO DE TOTALES DE PROFORMA
-- ============================================================================

CREATE OR REPLACE FUNCTION fn_recalcular_totales_proforma(p_proforma_id BIGINT)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE proformas
       SET subtotal = COALESCE((
               SELECT SUM(cantidad * precio_unitario)
                 FROM proformas_detalle
                WHERE proforma_id = p_proforma_id
           ), 0),
           descuento_total = COALESCE((
               SELECT SUM(descuento)
                 FROM proformas_detalle
                WHERE proforma_id = p_proforma_id
           ), 0),
           total = COALESCE((
               SELECT SUM(total)
                 FROM proformas_detalle
                WHERE proforma_id = p_proforma_id
           ), 0)
     WHERE id = p_proforma_id;
END;
$$;

CREATE OR REPLACE FUNCTION fn_trigger_recalcular_proforma()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        PERFORM fn_recalcular_totales_proforma(OLD.proforma_id);
        RETURN OLD;
    END IF;

    PERFORM fn_recalcular_totales_proforma(NEW.proforma_id);
    IF TG_OP = 'UPDATE' AND OLD.proforma_id <> NEW.proforma_id THEN
        PERFORM fn_recalcular_totales_proforma(OLD.proforma_id);
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_recalcular_proforma
AFTER INSERT OR UPDATE OR DELETE ON proformas_detalle
FOR EACH ROW
EXECUTE FUNCTION fn_trigger_recalcular_proforma();

-- ============================================================================
-- 18. PROTECCION Y ACTUALIZACION DEL STOCK
-- ============================================================================

-- productos.stock es una proyeccion de movimientos_stock. No se permite crear
-- un producto con stock inicial distinto de cero ni modificar stock directamente.
CREATE OR REPLACE FUNCTION fn_proteger_stock_producto()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_contexto TEXT;
BEGIN
    IF TG_OP = 'INSERT' THEN
        IF NEW.stock <> 0 THEN
            RAISE EXCEPTION 'El stock inicial de un producto debe ser 0. Use un movimiento CARGA_INICIAL';
        END IF;
        RETURN NEW;
    END IF;

    IF NEW.stock IS DISTINCT FROM OLD.stock THEN
        v_contexto := current_setting('homex.stock_update_context', TRUE);
        IF COALESCE(v_contexto, '') <> 'MOVIMIENTO_STOCK' THEN
            RAISE EXCEPTION 'productos.stock no puede modificarse directamente. Registre un movimiento de stock';
        END IF;
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_proteger_stock_producto
BEFORE INSERT OR UPDATE OF stock ON productos
FOR EACH ROW
EXECUTE FUNCTION fn_proteger_stock_producto();

CREATE OR REPLACE FUNCTION fn_validar_movimiento_stock()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_tipo TEXT;
    v_estado_pedido TEXT;
    v_requerido NUMERIC(12,3);
BEGIN
    IF NOT fn_catalogo_valor_pertenece(NEW.tipo_movimiento_id, 'TIPO_MOVIMIENTO') THEN
        RAISE EXCEPTION 'tipo_movimiento_id % no pertenece a TIPO_MOVIMIENTO activo', NEW.tipo_movimiento_id;
    END IF;

    v_tipo := fn_catalogo_codigo_valor(NEW.tipo_movimiento_id, 'TIPO_MOVIMIENTO');

    IF v_tipo = 'VENTA' THEN
        IF NEW.pedido_id IS NULL THEN
            RAISE EXCEPTION 'Un movimiento VENTA requiere pedido_id';
        END IF;
        IF NEW.cantidad >= 0 THEN
            RAISE EXCEPTION 'Un movimiento VENTA debe tener cantidad negativa';
        END IF;

        SELECT fn_catalogo_codigo_valor(pe.estado_id, 'ESTADO_PEDIDO')
          INTO v_estado_pedido
          FROM pedidos pe
         WHERE pe.id = NEW.pedido_id;

        IF v_estado_pedido IS DISTINCT FROM 'CONFIRMADO' THEN
            RAISE EXCEPTION 'Un movimiento VENTA solo puede asociarse a un pedido CONFIRMADO';
        END IF;

        SELECT SUM(pd.cantidad)::NUMERIC(12,3)
          INTO v_requerido
          FROM pedidos pe
          JOIN proformas_detalle pd ON pd.proforma_id = pe.proforma_id
         WHERE pe.id = NEW.pedido_id
           AND pd.producto_id = NEW.producto_id;

        IF v_requerido IS NULL THEN
            RAISE EXCEPTION 'El producto % no pertenece al pedido %', NEW.producto_id, NEW.pedido_id;
        END IF;

        IF NEW.cantidad <> -v_requerido THEN
            RAISE EXCEPTION 'La salida VENTA del producto % debe ser exactamente -% para el pedido %',
                NEW.producto_id, v_requerido, NEW.pedido_id;
        END IF;

    ELSIF v_tipo = 'CARGA_INICIAL' THEN
        IF NEW.pedido_id IS NOT NULL THEN
            RAISE EXCEPTION 'CARGA_INICIAL no debe asociarse a un pedido';
        END IF;
        IF NEW.cantidad <= 0 THEN
            RAISE EXCEPTION 'CARGA_INICIAL debe tener cantidad positiva';
        END IF;

    ELSIF v_tipo = 'AJUSTE' THEN
        IF NEW.pedido_id IS NOT NULL THEN
            RAISE EXCEPTION 'AJUSTE no debe asociarse a un pedido';
        END IF;
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_validar_movimiento_stock
BEFORE INSERT ON movimientos_stock
FOR EACH ROW
EXECUTE FUNCTION fn_validar_movimiento_stock();

CREATE OR REPLACE FUNCTION fn_actualizar_stock_desde_movimiento()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_stock NUMERIC(12,3);
BEGIN
    SELECT stock
      INTO v_stock
      FROM productos
     WHERE id = NEW.producto_id
     FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Producto % no existe', NEW.producto_id;
    END IF;

    IF v_stock + NEW.cantidad < 0 THEN
        RAISE EXCEPTION 'Stock insuficiente para producto %: disponible %, movimiento %',
            NEW.producto_id, v_stock, NEW.cantidad;
    END IF;

    PERFORM set_config('homex.stock_update_context', 'MOVIMIENTO_STOCK', TRUE);

    UPDATE productos
       SET stock = v_stock + NEW.cantidad
     WHERE id = NEW.producto_id;

    PERFORM set_config('homex.stock_update_context', '', TRUE);

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_actualizar_stock_desde_movimiento
AFTER INSERT ON movimientos_stock
FOR EACH ROW
EXECUTE FUNCTION fn_actualizar_stock_desde_movimiento();

-- El historial de stock es inmutable. Un error se corrige con un nuevo AJUSTE.
CREATE OR REPLACE FUNCTION fn_bloquear_mutacion_movimiento_stock()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'Los movimientos de stock son inmutables. Registre un AJUSTE para corregir un error';
END;
$$;

CREATE TRIGGER trg_bloquear_update_movimiento_stock
BEFORE UPDATE ON movimientos_stock
FOR EACH ROW
EXECUTE FUNCTION fn_bloquear_mutacion_movimiento_stock();

CREATE TRIGGER trg_bloquear_delete_movimiento_stock
BEFORE DELETE ON movimientos_stock
FOR EACH ROW
EXECUTE FUNCTION fn_bloquear_mutacion_movimiento_stock();

-- ============================================================================
-- 19. PEDIDOS: ESTADO, TRANSICIONES Y DESCUENTO DE STOCK
-- ============================================================================

CREATE OR REPLACE FUNCTION fn_validar_transicion_config_pedido()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF NOT fn_catalogo_valor_pertenece(NEW.estado_origen_id, 'ESTADO_PEDIDO') THEN
        RAISE EXCEPTION 'estado_origen_id % no pertenece a ESTADO_PEDIDO activo', NEW.estado_origen_id;
    END IF;
    IF NOT fn_catalogo_valor_pertenece(NEW.estado_destino_id, 'ESTADO_PEDIDO') THEN
        RAISE EXCEPTION 'estado_destino_id % no pertenece a ESTADO_PEDIDO activo', NEW.estado_destino_id;
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_validar_transicion_config_pedido
BEFORE INSERT OR UPDATE ON transiciones_estado_pedido
FOR EACH ROW
EXECUTE FUNCTION fn_validar_transicion_config_pedido();


CREATE OR REPLACE FUNCTION fn_validar_nuevo_pedido()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_estado_proforma TEXT;
    v_estado_pedido TEXT;
BEGIN
    IF NOT fn_catalogo_valor_pertenece(NEW.estado_id, 'ESTADO_PEDIDO') THEN
        RAISE EXCEPTION 'estado_id % no pertenece a ESTADO_PEDIDO activo', NEW.estado_id;
    END IF;

    v_estado_pedido := fn_catalogo_codigo_valor(NEW.estado_id, 'ESTADO_PEDIDO');
    IF v_estado_pedido <> 'CONFIRMADO' THEN
        RAISE EXCEPTION 'Un nuevo pedido debe crearse en estado CONFIRMADO';
    END IF;

    SELECT fn_catalogo_codigo_valor(p.estado_id, 'ESTADO_PROFORMA')
      INTO v_estado_proforma
      FROM proformas p
     WHERE p.id = NEW.proforma_id;

    IF v_estado_proforma IS DISTINCT FROM 'APROBADA' THEN
        RAISE EXCEPTION 'Solo una proforma APROBADA puede generar un pedido';
    END IF;

    IF NEW.fecha_confirmacion IS NULL THEN
        NEW.fecha_confirmacion := CURRENT_TIMESTAMP;
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_validar_nuevo_pedido
BEFORE INSERT ON pedidos
FOR EACH ROW
EXECUTE FUNCTION fn_validar_nuevo_pedido();

CREATE OR REPLACE FUNCTION fn_validar_transicion_pedido()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.estado_id IS NOT DISTINCT FROM OLD.estado_id THEN
        RETURN NEW;
    END IF;

    IF NOT fn_catalogo_valor_pertenece(NEW.estado_id, 'ESTADO_PEDIDO') THEN
        RAISE EXCEPTION 'estado_id % no pertenece a ESTADO_PEDIDO activo', NEW.estado_id;
    END IF;

    IF NOT EXISTS (
        SELECT 1
          FROM transiciones_estado_pedido t
         WHERE t.estado_origen_id = OLD.estado_id
           AND t.estado_destino_id = NEW.estado_id
    ) THEN
        RAISE EXCEPTION 'Transicion de estado de pedido no permitida: % -> %',
            fn_catalogo_codigo_valor(OLD.estado_id, 'ESTADO_PEDIDO'),
            fn_catalogo_codigo_valor(NEW.estado_id, 'ESTADO_PEDIDO');
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_validar_transicion_pedido
BEFORE UPDATE OF estado_id ON pedidos
FOR EACH ROW
EXECUTE FUNCTION fn_validar_transicion_pedido();

CREATE OR REPLACE FUNCTION fn_confirmar_pedido_descontar_stock()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_tipo_venta BIGINT;
    v_stock NUMERIC(12,3);
    v_requerido NUMERIC(12,3);
    v_producto_id BIGINT;
BEGIN
    IF NOT fn_catalogo_valor_es(NEW.estado_id, 'ESTADO_PEDIDO', 'CONFIRMADO') THEN
        RETURN NEW;
    END IF;

    SELECT cv.id
      INTO v_tipo_venta
      FROM catalogo_valores cv
      JOIN catalogo_conceptos cc ON cc.id = cv.concepto_id
     WHERE cc.codigo = 'TIPO_MOVIMIENTO'
       AND cv.codigo = 'VENTA'
       AND cc.activo = TRUE
       AND cv.activo = TRUE;

    IF v_tipo_venta IS NULL THEN
        RAISE EXCEPTION 'No existe el tipo de movimiento VENTA activo';
    END IF;

    -- Primero se bloquean y validan TODAS las existencias. Si una falla, la
    -- transaccion completa se revierte, incluida la aprobacion de la proforma.
    FOR v_producto_id, v_requerido IN
        SELECT pd.producto_id, SUM(pd.cantidad)::NUMERIC(12,3)
          FROM proformas_detalle pd
         WHERE pd.proforma_id = NEW.proforma_id
           AND pd.producto_id IS NOT NULL
         GROUP BY pd.producto_id
         ORDER BY pd.producto_id
    LOOP
        SELECT stock
          INTO v_stock
          FROM productos
         WHERE id = v_producto_id
         FOR UPDATE;

        IF NOT FOUND THEN
            RAISE EXCEPTION 'Producto % no existe', v_producto_id;
        END IF;

        IF v_stock < v_requerido THEN
            RAISE EXCEPTION 'No se puede aprobar la proforma: stock insuficiente para producto %. Disponible: %, requerido: %',
                v_producto_id, v_stock, v_requerido;
        END IF;
    END LOOP;

    -- Solo despues de validar todo el pedido se crean las salidas.
    FOR v_producto_id, v_requerido IN
        SELECT pd.producto_id, SUM(pd.cantidad)::NUMERIC(12,3)
          FROM proformas_detalle pd
         WHERE pd.proforma_id = NEW.proforma_id
           AND pd.producto_id IS NOT NULL
         GROUP BY pd.producto_id
         ORDER BY pd.producto_id
    LOOP
        INSERT INTO movimientos_stock (
            producto_id,
            fecha,
            tipo_movimiento_id,
            cantidad,
            pedido_id,
            observaciones,
            created_by_id
        ) VALUES (
            v_producto_id,
            CURRENT_TIMESTAMP,
            v_tipo_venta,
            -v_requerido,
            NEW.id,
            'Salida por aprobacion de proforma y confirmacion del pedido #' || NEW.id,
            COALESCE(NEW.updated_by_id, NEW.created_by_id)
        );
    END LOOP;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_confirmar_pedido_descontar_stock
AFTER INSERT ON pedidos
FOR EACH ROW
EXECUTE FUNCTION fn_confirmar_pedido_descontar_stock();

-- La aprobacion de la proforma es el evento empresarial que crea el pedido.
-- Si la creacion del pedido o cualquier salida de stock falla, la excepcion
-- revierte tambien el cambio de estado de la proforma.
CREATE OR REPLACE FUNCTION fn_aprobar_proforma_crear_pedido()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_estado_confirmado BIGINT;
BEGIN
    IF NOT fn_catalogo_valor_es(NEW.estado_id, 'ESTADO_PROFORMA', 'APROBADA')
       OR fn_catalogo_valor_es(OLD.estado_id, 'ESTADO_PROFORMA', 'APROBADA') THEN
        RETURN NEW;
    END IF;

    IF EXISTS (SELECT 1 FROM pedidos pe WHERE pe.proforma_id = NEW.id) THEN
        RAISE EXCEPTION 'La proforma % ya tiene un pedido asociado', NEW.id;
    END IF;

    SELECT cv.id
      INTO v_estado_confirmado
      FROM catalogo_valores cv
      JOIN catalogo_conceptos cc ON cc.id = cv.concepto_id
     WHERE cc.codigo = 'ESTADO_PEDIDO'
       AND cv.codigo = 'CONFIRMADO'
       AND cc.activo = TRUE
       AND cv.activo = TRUE;

    IF v_estado_confirmado IS NULL THEN
        RAISE EXCEPTION 'No existe el estado CONFIRMADO activo para pedidos';
    END IF;

    INSERT INTO pedidos (
        proforma_id,
        fecha_confirmacion,
        estado_id,
        created_by_id,
        updated_by_id
    ) VALUES (
        NEW.id,
        CURRENT_TIMESTAMP,
        v_estado_confirmado,
        COALESCE(NEW.updated_by_id, NEW.created_by_id),
        COALESCE(NEW.updated_by_id, NEW.created_by_id)
    );

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_aprobar_proforma_crear_pedido
AFTER UPDATE OF estado_id ON proformas
FOR EACH ROW
EXECUTE FUNCTION fn_aprobar_proforma_crear_pedido();

-- ============================================================================
-- 20. VALIDACIONES DE RECIBOS
-- ============================================================================

CREATE OR REPLACE FUNCTION fn_validar_recibo_pago()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF NOT fn_catalogo_valor_pertenece(NEW.tipo_pago_id, 'TIPO_PAGO') THEN
        RAISE EXCEPTION 'tipo_pago_id % no pertenece a TIPO_PAGO activo', NEW.tipo_pago_id;
    END IF;

    IF fn_catalogo_valor_es(NEW.tipo_pago_id, 'TIPO_PAGO', 'CHEQUE') THEN
        IF NULLIF(BTRIM(NEW.numero_cheque), '') IS NULL THEN
            RAISE EXCEPTION 'Un recibo con pago CHEQUE requiere numero_cheque';
        END IF;
        IF NULLIF(BTRIM(NEW.banco), '') IS NULL THEN
            RAISE EXCEPTION 'Un recibo con pago CHEQUE requiere banco';
        END IF;
    ELSE
        NEW.numero_cheque := NULL;
        NEW.banco := NULL;
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_validar_recibo_pago
BEFORE INSERT OR UPDATE ON recibos
FOR EACH ROW
EXECUTE FUNCTION fn_validar_recibo_pago();

-- ============================================================================
-- 21. COMENTARIOS DE DISEÑO
-- ============================================================================

COMMENT ON TABLE catalogo_conceptos IS
'Define clases de valores configurables. No representa entidades de negocio.';

COMMENT ON TABLE catalogo_valores IS
'Contiene los valores concretos pertenecientes a cada concepto configurable.';

COMMENT ON TABLE productos IS
'Productos maestros con existencia: sillas, pisos y otros. Los muebles personalizados no se almacenan como productos.';

COMMENT ON TABLE productos_piso IS
'Ficha estructurada de pisos. El stock y la venta se manejan en cajas; m2_por_caja permite mostrar cobertura sin usar m2 como unidad transaccional.';

COMMENT ON TABLE movimientos_stock IS
'Historial inmutable de entradas y salidas que constituye la unica via permitida para modificar productos.stock.';

COMMENT ON TABLE proformas IS
'Documento comercial de cotizacion. Al entrar en APROBADA se crea automaticamente un pedido CONFIRMADO dentro de la misma transaccion.';

COMMENT ON TABLE pedidos IS
'Representa la aceptacion de una proforma. Su creacion en CONFIRMADO provoca la salida de stock de productos de catalogo.';

COMMENT ON TABLE ordenes_trabajo IS
'Documento interno de fabricacion/preparacion basado en un pedido. El numero de proforma se obtiene mediante pedido -> proforma y no se duplica.';

COMMENT ON TABLE notas_entrega IS
'Documento de entrega. Cliente, proforma y detalle se obtienen a traves del pedido.';

COMMENT ON TABLE recibos IS
'Recibo digital a nivel de datos. La moneda se hereda de la proforma y no se duplica en esta tabla.';

COMMENT ON TABLE capturas IS
'Captura individual de voz/texto para un producto, con transcripcion, normalizacion, latencias y salida bruta del modelo.';

COMMENT ON TABLE items_ia IS
'Resultado estructurado de un unico producto detectado por la IA en una captura.';

COMMENT ON TABLE items_humano IS
'Version final corregida por el vendedor y metricas de intervencion a nivel de item.';

COMMENT ON TABLE evaluaciones_nlp IS
'Metricas consolidadas de calidad e intervencion humana para una captura.';

COMMENT ON TABLE mediciones_proceso IS
'Mediciones para comparar el procedimiento manual con el proceso NLP + HITL.';

COMMIT;

-- ============================================================================
-- NOTA SOBRE DJANGO
-- ============================================================================
-- Este script NO crea auth_user, auth_group ni tablas intermedias de Django.
-- Los campos created_by_id / updated_by_id se mantienen como BIGINT hasta que
-- los modelos Django los relacionen con settings.AUTH_USER_MODEL.
--
-- Django incorporara posteriormente, donde corresponda:
--     created_at = models.DateTimeField(auto_now_add=True)
--     updated_at = models.DateTimeField(auto_now=True)
--
-- Si el proyecto usa AutoField de 32 bits en lugar de BigAutoField, se debera
-- adaptar el tipo fisico de las referencias de usuario.
-- ============================================================================
